language: python
python: 3.8
# see https://docs.travis-ci.com/user/languages/python/#dependency-management
install:
- pip install -r requirements.txt
script:
- make html
- cp -r images _build/html/
- cp CNAME _build/html/
- touch _build/html/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    all_branches: true
  local_dir: _build/html
